[window]
padding = { x = 5, y = 5}

[font]
size = 10

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[colors.primary]
background = "#222222"
foreground = "#9b8d7f"
