[window]
padding = { x = 5, y = 5}

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
bold = { family = "JetBrainsMonoNerdFont", style = "Bold" }
italic = { family = "JetBrainsMonoNerdFont", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNerdFont", style = "Bold Italic" }
size = 10

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[colors.primary]
background = "#100f0f"
foreground = "#9b8d7f"
