[window]
padding = { x = 10, y = 10}

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
bold = { family = "JetBrainsMonoNerdFont", style = "Bold" }
italic = { family = "JetBrainsMonoNerdFont", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNerdFont", style = "Bold Italic" }
size = 25

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[colors.primary]
background = "#100f0f"
# foreground = "#ebdbb2"
foreground = "#ffffff"
