set -g mouse on
set -g status-left ""
set -g status-right ""
set -g status-justify centre
set -g status-style fg=colour255
set-option -g status-position top

bind-key S command-prompt -I "#S" "rename-session '%%'"
bind-key W command-prompt -I "#W" "rename-window '%%'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'
